# demo: charinterval=0
workon py36
export PROFILE_PROMPT=psss
c() { clear; }; export -f c
e() { exit; }; export -f e
shellman() { command shellman -c shellman.credits="" "$@"; }; export -f shellman
c  # demo: charinterval=0.05

termtosvg -g 80x20 demo.svg  # demo: sleep 2
cat demo.bash  # demo: sleep 3
c
grep '##' demo.bash  # demo: sleep 3
c
shellman demo.bash  # demo: sleep 2
c
shellman demo.bash -t manpage # demo: sleep 2
c
man <(shellman demo.bash -t manpage) # demo: sleep 3
qc
shellman demo.bash -t wikipage  # demo: sleep 3
e  # demo: sleep 1

