site_name: "shellman"
site_description: "Write documentation in comments and render it with templates."
site_url: "https://pawamoy.github.io/shellman"
repo_url: "https://github.com/pawamoy/shellman"
repo_name: "pawamoy/shellman"

nav:
  - Overview: index.md
  - Reference:
    - cli.py: reference/cli.md
    - context.py: refenrece/context.md
    - reader.py: refenrece/reader.md
    - tags.py: refenrece/tags.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/shellman
